#!/bin/bash

AMOUNT_LEFT=$(cat /sys/class/power_supply/BAT0/uevent | awk '/POWER_SUPPLY_CHARGE_NOW/ {print $1}' | cut -d'=' -f2)

AMOUNT_TOTAL=$(cat /sys/class/power_supply/BAT0/uevent | awk '/POWER_SUPPLY_CHARGE_FULL=/ {print $1}' | cut -d'=' -f2)

python -c "print('{:2.2f}'.format(1.0*$(echo $AMOUNT_LEFT)/$(echo $AMOUNT_TOTAL)*100))"
